=== sbswcidr/auto-comet/trunk/source/auto-comet/src/org/auto/comet/xml/dataSync.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.thunisoft.com/sync" targetNamespace="http://www.thunisoft.com/sync">

	<xsd:import namespace="http://www.w3.org/XML/1998/namespace" />

	<xsd:annotation>
		<xsd:documentation>
			<![CDATA[DataSync XML Beans Schema]]>
		</xsd:documentation>
	</xsd:annotation>

	<xsd:element name="sources">
		<xsd:annotation>
			<xsd:documentation>
				<![CDATA[同步实体根]]>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:choice minOccurs="0" maxOccurs="unbounded">
					<xsd:element ref="source" minOccurs="0" maxOccurs="unbounded" />
					<xsd:any namespace="##other" processContents="strict"
						minOccurs="0" maxOccurs="unbounded" />
				</xsd:choice>
			</xsd:sequence>
			<xsd:anyAttribute namespace="##other"
				processContents="lax" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="source">
		<xsd:annotation>
			<xsd:documentation>
				<![CDATA[需要同步的实体]]>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:choice minOccurs="0" maxOccurs="unbounded">
					<xsd:element ref="target" maxOccurs="unbounded" />
					<xsd:any namespace="##other" processContents="strict"
						minOccurs="0" maxOccurs="unbounded" />
				</xsd:choice>
			</xsd:sequence>
			<xsd:attribute name="class" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation source="java:java.lang.Class">
						<![CDATA[需要同步的实体类，类全称！]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="target">
		<xsd:annotation>
			<xsd:documentation>
			<![CDATA[同步到的目标实体]]>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="property" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="class" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation source="java:java.lang.Class">
						<![CDATA[同步到的目标类，类全称！]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="auto-convert" type="xsd:boolean">
				<xsd:annotation>
					<xsd:documentation source="java:java.lang.Class">
						<![CDATA[是否自动转化名称相同的属性，默认true]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="property">
		<xsd:annotation>
			<xsd:documentation source="java:java.lang.Class">
				<![CDATA[需要转换的属性]]>
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:attribute name="name" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation source="java:java.lang.Class">
						<![CDATA[实体属性名称 ]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="converter-name" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation source="java:java.lang.Class">
						<![CDATA[转换器名称]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="sourse" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation source="java:java.lang.Class">
						<![CDATA[源实体属性名称 ]]>
					</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== sbswcidr/auto-comet/trunk/source/auto-comet/src/org/auto/dataSync-ywgy.sync.xml
<?xml version="1.0" encoding="UTF-8"?>
<sources xmlns="http://www.thunisoft.com/sync" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:mytestin="http://www.thunisoft.com/test"
	xsi:schemaLocation="http://www.thunisoft.com/sync
	http://www.thunisoft.com/sync/dataSync.xsd
	http://www.thunisoft.com/test
	http://www.thunisoft.com/test/testInsid.xsd">

	<mytestin:TestDataSync>
	<mytestin:inTest></mytestin:inTest>
	</mytestin:TestDataSync>

	<!-- 办案中发现线索 -->
	<source
		class="com.thunisoft.np.datamodel.cases.jcy.ywgy.bazfxxs.TYwgyBazfxxsXs">
		<mytestin:TestDataSync></mytestin:TestDataSync>
		<target class="com.thunisoft.np.datamodel.cases.jcy.ywgy.hztj.TYwgyHztjAj"
			auto-convert="true">
			<!--受理日期-->
			<property name="DSarq" sourse="DDjrq" />
			<property name="CBhSar" sourse="CBhDjr" />
		</target>
	</source>

	<!-- 办案中发现线索.处理情况 -->
	<source
		class="com.thunisoft.np.datamodel.cases.jcy.ywgy.bazfxxs.TYwgyBazfxxsClqk">
		<target class="com.thunisoft.np.datamodel.cases.jcy.ywgy.hztj.TYwgyHztjAj"
			auto-convert="false">
			<property name="CBh" sourse="CBhAj" />
			<property name="NBjjl" sourse="NJl" />
			<property name="DBjrq" sourse="DRq" />
		</target>
	</source>

	<!-- 请示批复案件 -->
	<source class="com.thunisoft.np.datamodel.cases.jcy.ywgy.qspf.TYwgyQspfAj">
		<target class="com.thunisoft.np.datamodel.cases.jcy.ywgy.hztj.TYwgyHztjAj"
			auto-convert="true">
		</target>
	</source>

	<!-- 交督办案件标记 -->
	<source class="com.thunisoft.np.datamodel.cases.jcy.ywgy.TYwgyJdbaj">
		<target class="com.thunisoft.np.datamodel.cases.jcy.ywgy.hztj.TYwgyHztjAj"
			auto-convert="false">
			<property name="CBh" sourse="CBhAj" />
			<property name="NJdbBjlx" sourse="NBjlx" />
			<property name="CJdbAh" sourse="CJdbah" />
		</target>
	</source>

	<!--文书-->
	<source class="com.thunisoft.np.writ.datamodel.TYwgyWsqdWs">
		<target class="com.thunisoft.np.datamodel.cases.jcy.ywgy.hztj.TYwgyHztjAj"
			auto-convert="false">
			<property name="CBh" sourse="CBhAj" />
			<property name="NYxwstj" converter-name="wsCount" sourse="CBhAj" />
		</target>
	</source>

</sources>
